### ISSUE TITLE
Repostitory structure for v0014 is not compliant 

### ISSUE THREAD

**Issue by uav2608** [fwestenberg/reolink#20]
I tried to add repository through HACS but had 'Repostitory structure for v0014 is not compliant' error. I am using HA version 2020.12.7; HA OS version 5.9. Could not find any info in logs.

**Comment by fwestenberg** [comment]
This could also be a HACS issue. Read some people solved this with other repositories by reinstalling HACS.

**Comment by fwestenberg** [comment]
HACS should report version 0.10 as latest.

**Comment by uav2608** [comment]
I have HACS version 1.9.0 installed.

**Comment by fwestenberg** [comment]
Me too...

**Comment by fwestenberg** [comment]
V0014 refers to the wrong repository: reolink instead of reolink_dev. So probably a HACS caching thing on your installation. Please try to reinstall HACS first.

**Comment by uav2608** [comment]
I reinstalled HACS but did not help. will wait for other updates and will try later.

**Comment by svtesan** [comment]
@uav2608  You most certainly tried to add "https://github.com/fwestenberg/reolink" (this repo). This repo is just the python code. If you want the HACS integration, please use "https://github.com/fwestenberg/reolink_dev" (with _dev suffix) which is another repo. I got the same error and realized I was trying to add the python API instead of the integration repo. HTH

**Comment by uav2608** [comment]
thank you. it works now.

**Comment by uav2608** [comment]
thank you. it works now.
